package com.ycxy.wdgj.dao;

import com.ycxy.wdgj.taobao.domain.OnlineTrade;
import com.ycxy.wdgj.taobao.domain.OnlineTradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OnlineTradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_trade
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    long countByExample(OnlineTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_trade
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int deleteByExample(OnlineTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_trade
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_trade
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int insert(OnlineTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_trade
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int insertSelective(OnlineTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_trade
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    List<OnlineTrade> selectByExample(OnlineTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_trade
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    OnlineTrade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_trade
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") OnlineTrade record, @Param("example") OnlineTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_trade
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int updateByExample(@Param("record") OnlineTrade record, @Param("example") OnlineTradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_trade
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int updateByPrimaryKeySelective(OnlineTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_trade
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int updateByPrimaryKey(OnlineTrade record);
}