package com.ycxy.wdgj.dao;

import com.ycxy.wdgj.taobao.domain.OnlineOrder;
import com.ycxy.wdgj.taobao.domain.OnlineOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OnlineOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    long countByExample(OnlineOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int deleteByExample(OnlineOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int insert(OnlineOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int insertSelective(OnlineOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    List<OnlineOrder> selectByExample(OnlineOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    OnlineOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") OnlineOrder record, @Param("example") OnlineOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int updateByExample(@Param("record") OnlineOrder record, @Param("example") OnlineOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int updateByPrimaryKeySelective(OnlineOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    int updateByPrimaryKey(OnlineOrder record);
}