package com.ycxy.wdgj.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ycxy.wdgj.model.Product;
import com.ycxy.wdgj.model.ProductExample;

public interface ProductMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product
     * 
     * @mbg.generated Thu Feb 22 15:11:18 CST 2018
     */
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product
     * 
     * @mbg.generated Thu Feb 22 15:11:18 CST 2018
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product
     * 
     * @mbg.generated Thu Feb 22 15:11:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product
     * 
     * @mbg.generated Thu Feb 22 15:11:18 CST 2018
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product
     * 
     * @mbg.generated Thu Feb 22 15:11:18 CST 2018
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product
     * 
     * @mbg.generated Thu Feb 22 15:11:18 CST 2018
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product
     * 
     * @mbg.generated Thu Feb 22 15:11:18 CST 2018
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product
     * 
     * @mbg.generated Thu Feb 22 15:11:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product
     * 
     * @mbg.generated Thu Feb 22 15:11:18 CST 2018
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product
     * 
     * @mbg.generated Thu Feb 22 15:11:18 CST 2018
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product
     * 
     * @mbg.generated Thu Feb 22 15:11:18 CST 2018
     */
    int updateByPrimaryKey(Product record);

    /**
     * @param ids
     */
    void updateIsDeleteByPrimaryKeyList(@Param("ids") List<Integer> ids);
}