package com.ycxy.wdgj.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ycxy.wdgj.model.Shop;
import com.ycxy.wdgj.model.ShopExample;

public interface ShopMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * shop
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    long countByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * shop
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    int deleteByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * shop
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * shop
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * shop
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * shop
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    List<Shop> selectByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * shop
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    Shop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * shop
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") Shop record, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * shop
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    int updateByExample(@Param("record") Shop record, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * shop
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * shop
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    int updateByPrimaryKey(Shop record);

    /**
     * @param days
     * @return
     */
    Double selectCountMoney(@Param("shopId") Long shopId, @Param("days") int days);
}