package com.ycxy.wdgj.dao;

import com.ycxy.wdgj.model.TradeReceiver;
import com.ycxy.wdgj.model.TradeReceiverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeReceiverMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_receiver
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	long countByExample(TradeReceiverExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_receiver
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	int deleteByExample(TradeReceiverExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_receiver
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_receiver
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	int insert(TradeReceiver record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_receiver
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	int insertSelective(TradeReceiver record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_receiver
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	List<TradeReceiver> selectByExample(TradeReceiverExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_receiver
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	TradeReceiver selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_receiver
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TradeReceiver record, @Param("example") TradeReceiverExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_receiver
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	int updateByExample(@Param("record") TradeReceiver record, @Param("example") TradeReceiverExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_receiver
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	int updateByPrimaryKeySelective(TradeReceiver record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_receiver
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	int updateByPrimaryKey(TradeReceiver record);
}