package com.ycxy.wdgj.taobao.domain;

import java.util.Date;

public class OnlineOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.item_meal_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String itemMealName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pic_path
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String picPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.seller_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String sellerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.buyer_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String buyerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.refund_status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String refundStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.outer_iid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String outerIid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.snapshot_url
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String snapshotUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.snapshot
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String snapshot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.timeout_action_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Date timeoutActionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.buyer_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Boolean buyerRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.seller_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Boolean sellerRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.seller_type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String sellerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.cid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.sub_order_tax_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String subOrderTaxFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.sub_order_tax_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String subOrderTaxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.estimate_conTime
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String estimateContime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.oid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.title
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.iid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String iid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.price
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.num_Iid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Integer numIid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.item_meal_Id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String itemMealId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.sku_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.num
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.outer_skuId
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String outerSkuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.order_from
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String orderFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.total_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Double totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.payment
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Double payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.discount_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Double discountFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.adjust_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Double adjustFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.modified
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.sku_properties_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String skuPropertiesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.refund_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String refundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.isOversold
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String isoversold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.is_serviceOrder
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String isServiceorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.end_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.consign_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Date consignTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.id
     *
     * @return the value of online_order.id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.id
     *
     * @param id the value for online_order.id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.item_meal_name
     *
     * @return the value of online_order.item_meal_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getItemMealName() {
        return itemMealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.item_meal_name
     *
     * @param itemMealName the value for online_order.item_meal_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setItemMealName(String itemMealName) {
        this.itemMealName = itemMealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pic_path
     *
     * @return the value of online_order.pic_path
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pic_path
     *
     * @param picPath the value for online_order.pic_path
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.seller_nick
     *
     * @return the value of online_order.seller_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getSellerNick() {
        return sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.seller_nick
     *
     * @param sellerNick the value for online_order.seller_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.buyer_nick
     *
     * @return the value of online_order.buyer_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.buyer_nick
     *
     * @param buyerNick the value for online_order.buyer_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.refund_status
     *
     * @return the value of online_order.refund_status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.refund_status
     *
     * @param refundStatus the value for online_order.refund_status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.outer_iid
     *
     * @return the value of online_order.outer_iid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getOuterIid() {
        return outerIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.outer_iid
     *
     * @param outerIid the value for online_order.outer_iid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setOuterIid(String outerIid) {
        this.outerIid = outerIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.snapshot_url
     *
     * @return the value of online_order.snapshot_url
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getSnapshotUrl() {
        return snapshotUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.snapshot_url
     *
     * @param snapshotUrl the value for online_order.snapshot_url
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSnapshotUrl(String snapshotUrl) {
        this.snapshotUrl = snapshotUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.snapshot
     *
     * @return the value of online_order.snapshot
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getSnapshot() {
        return snapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.snapshot
     *
     * @param snapshot the value for online_order.snapshot
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSnapshot(String snapshot) {
        this.snapshot = snapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.timeout_action_time
     *
     * @return the value of online_order.timeout_action_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Date getTimeoutActionTime() {
        return timeoutActionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.timeout_action_time
     *
     * @param timeoutActionTime the value for online_order.timeout_action_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setTimeoutActionTime(Date timeoutActionTime) {
        this.timeoutActionTime = timeoutActionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.buyer_rate
     *
     * @return the value of online_order.buyer_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Boolean getBuyerRate() {
        return buyerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.buyer_rate
     *
     * @param buyerRate the value for online_order.buyer_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setBuyerRate(Boolean buyerRate) {
        this.buyerRate = buyerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.seller_rate
     *
     * @return the value of online_order.seller_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Boolean getSellerRate() {
        return sellerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.seller_rate
     *
     * @param sellerRate the value for online_order.seller_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSellerRate(Boolean sellerRate) {
        this.sellerRate = sellerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.seller_type
     *
     * @return the value of online_order.seller_type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getSellerType() {
        return sellerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.seller_type
     *
     * @param sellerType the value for online_order.seller_type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSellerType(String sellerType) {
        this.sellerType = sellerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.cid
     *
     * @return the value of online_order.cid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.cid
     *
     * @param cid the value for online_order.cid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.sub_order_tax_fee
     *
     * @return the value of online_order.sub_order_tax_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getSubOrderTaxFee() {
        return subOrderTaxFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.sub_order_tax_fee
     *
     * @param subOrderTaxFee the value for online_order.sub_order_tax_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSubOrderTaxFee(String subOrderTaxFee) {
        this.subOrderTaxFee = subOrderTaxFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.sub_order_tax_rate
     *
     * @return the value of online_order.sub_order_tax_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getSubOrderTaxRate() {
        return subOrderTaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.sub_order_tax_rate
     *
     * @param subOrderTaxRate the value for online_order.sub_order_tax_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSubOrderTaxRate(String subOrderTaxRate) {
        this.subOrderTaxRate = subOrderTaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.estimate_conTime
     *
     * @return the value of online_order.estimate_conTime
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getEstimateContime() {
        return estimateContime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.estimate_conTime
     *
     * @param estimateContime the value for online_order.estimate_conTime
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setEstimateContime(String estimateContime) {
        this.estimateContime = estimateContime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.oid
     *
     * @return the value of online_order.oid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.oid
     *
     * @param oid the value for online_order.oid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.status
     *
     * @return the value of online_order.status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.status
     *
     * @param status the value for online_order.status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.title
     *
     * @return the value of online_order.title
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.title
     *
     * @param title the value for online_order.title
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.type
     *
     * @return the value of online_order.type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.type
     *
     * @param type the value for online_order.type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.iid
     *
     * @return the value of online_order.iid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.iid
     *
     * @param iid the value for online_order.iid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setIid(String iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.price
     *
     * @return the value of online_order.price
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.price
     *
     * @param price the value for online_order.price
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.num_Iid
     *
     * @return the value of online_order.num_Iid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Integer getNumIid() {
        return numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.num_Iid
     *
     * @param numIid the value for online_order.num_Iid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setNumIid(Integer numIid) {
        this.numIid = numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.item_meal_Id
     *
     * @return the value of online_order.item_meal_Id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getItemMealId() {
        return itemMealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.item_meal_Id
     *
     * @param itemMealId the value for online_order.item_meal_Id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setItemMealId(String itemMealId) {
        this.itemMealId = itemMealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.sku_id
     *
     * @return the value of online_order.sku_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.sku_id
     *
     * @param skuId the value for online_order.sku_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.num
     *
     * @return the value of online_order.num
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.num
     *
     * @param num the value for online_order.num
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.outer_skuId
     *
     * @return the value of online_order.outer_skuId
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getOuterSkuid() {
        return outerSkuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.outer_skuId
     *
     * @param outerSkuid the value for online_order.outer_skuId
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setOuterSkuid(String outerSkuid) {
        this.outerSkuid = outerSkuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.order_from
     *
     * @return the value of online_order.order_from
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getOrderFrom() {
        return orderFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.order_from
     *
     * @param orderFrom the value for online_order.order_from
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setOrderFrom(String orderFrom) {
        this.orderFrom = orderFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.total_fee
     *
     * @return the value of online_order.total_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Double getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.total_fee
     *
     * @param totalFee the value for online_order.total_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.payment
     *
     * @return the value of online_order.payment
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Double getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.payment
     *
     * @param payment the value for online_order.payment
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setPayment(Double payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.discount_fee
     *
     * @return the value of online_order.discount_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Double getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.discount_fee
     *
     * @param discountFee the value for online_order.discount_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setDiscountFee(Double discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.adjust_fee
     *
     * @return the value of online_order.adjust_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Double getAdjustFee() {
        return adjustFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.adjust_fee
     *
     * @param adjustFee the value for online_order.adjust_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setAdjustFee(Double adjustFee) {
        this.adjustFee = adjustFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.modified
     *
     * @return the value of online_order.modified
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.modified
     *
     * @param modified the value for online_order.modified
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.sku_properties_name
     *
     * @return the value of online_order.sku_properties_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getSkuPropertiesName() {
        return skuPropertiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.sku_properties_name
     *
     * @param skuPropertiesName the value for online_order.sku_properties_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSkuPropertiesName(String skuPropertiesName) {
        this.skuPropertiesName = skuPropertiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.refund_id
     *
     * @return the value of online_order.refund_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.refund_id
     *
     * @param refundId the value for online_order.refund_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.isOversold
     *
     * @return the value of online_order.isOversold
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getIsoversold() {
        return isoversold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.isOversold
     *
     * @param isoversold the value for online_order.isOversold
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setIsoversold(String isoversold) {
        this.isoversold = isoversold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.is_serviceOrder
     *
     * @return the value of online_order.is_serviceOrder
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getIsServiceorder() {
        return isServiceorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.is_serviceOrder
     *
     * @param isServiceorder the value for online_order.is_serviceOrder
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setIsServiceorder(String isServiceorder) {
        this.isServiceorder = isServiceorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.end_time
     *
     * @return the value of online_order.end_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.end_time
     *
     * @param endTime the value for online_order.end_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.consign_time
     *
     * @return the value of online_order.consign_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Date getConsignTime() {
        return consignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.consign_time
     *
     * @param consignTime the value for online_order.consign_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setConsignTime(Date consignTime) {
        this.consignTime = consignTime;
    }
}