package com.ycxy.wdgj.taobao.domain;

import java.io.Serializable;
import java.util.Date;

public class OnlineTrade implements Serializable {
    private OnlineOrder[] orders;

    public OnlineOrder[] getOrders() {
        return orders;
    }

    public void setOrders(OnlineOrder[] orders) {
        this.orders = orders;
    }

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.seller_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String sellerNick;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.pic_path
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String picPath;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.payment
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String payment;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.seller_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Boolean sellerRate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.post_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Double postFee;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.receiver_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.receiver_state
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String receiverState;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.receiver_address
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String receiverAddress;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.receiver_zip
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String receiverZip;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.receiver_mobile
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String receiverMobile;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.receiver_phone
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.consign_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String consignTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.received_payment
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String receivedPayment;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.receiver_country
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String receiverCountry;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.receiver_town
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String receiverTown;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.order_tax_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String orderTaxFee;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.shop_pick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String shopPick;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.tid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.num
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.numIid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Integer numiid;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.title
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.price
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.discount_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Double discountFee;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.total_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Double totalFee;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.created
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.pay_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.modified
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.end_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.seller_flag
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String sellerFlag;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.buyer_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String buyerNick;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.has_buyer_message
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String hasBuyerMessage;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.credit_card_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Double creditCardFee;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.step_trade_status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String stepTradeStatus;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.step_paid_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Double stepPaidFee;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.mark_desc
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String markDesc;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.shipping_type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String shippingType;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.adjust_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Double adjustFee;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.trade_from
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String tradeFrom;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.buyer_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Boolean buyerRate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.receiver_city
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String receiverCity;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.receiver_district
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String receiverDistrict;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.o2o
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String o2o;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.o2o_guide_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String o2oGuideId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.o2o_shop_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String o2oShopId;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.o2o_guide_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String o2oGuideName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.o2o_shop_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String o2oShopName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.o2o_delivery
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String o2oDelivery;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.rx_audit_status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String rxAuditStatus;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.post_gate_declare
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Boolean postGateDeclare;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.cross_bonded_declare
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private Boolean crossBondedDeclare;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.order_tax_promotion_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String orderTaxPromotionFee;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * online_trade.service_type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    private String serviceType;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.id
     *
     * @return the value of online_trade.id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.id
     *
     * @param id
     *            the value for online_trade.id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.seller_nick
     *
     * @return the value of online_trade.seller_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getSellerNick() {
        return sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.seller_nick
     *
     * @param sellerNick
     *            the value for online_trade.seller_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.pic_path
     *
     * @return the value of online_trade.pic_path
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.pic_path
     *
     * @param picPath
     *            the value for online_trade.pic_path
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.payment
     *
     * @return the value of online_trade.payment
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.payment
     *
     * @param payment
     *            the value for online_trade.payment
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setPayment(String payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.seller_rate
     *
     * @return the value of online_trade.seller_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Boolean getSellerRate() {
        return sellerRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.seller_rate
     *
     * @param sellerRate
     *            the value for online_trade.seller_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSellerRate(Boolean sellerRate) {
        this.sellerRate = sellerRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.post_fee
     *
     * @return the value of online_trade.post_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Double getPostFee() {
        return postFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.post_fee
     *
     * @param postFee
     *            the value for online_trade.post_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setPostFee(Double postFee) {
        this.postFee = postFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.receiver_name
     *
     * @return the value of online_trade.receiver_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.receiver_name
     *
     * @param receiverName
     *            the value for online_trade.receiver_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.receiver_state
     *
     * @return the value of online_trade.receiver_state
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getReceiverState() {
        return receiverState;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.receiver_state
     *
     * @param receiverState
     *            the value for online_trade.receiver_state
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setReceiverState(String receiverState) {
        this.receiverState = receiverState;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.receiver_address
     *
     * @return the value of online_trade.receiver_address
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.receiver_address
     *
     * @param receiverAddress
     *            the value for online_trade.receiver_address
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.receiver_zip
     *
     * @return the value of online_trade.receiver_zip
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.receiver_zip
     *
     * @param receiverZip
     *            the value for online_trade.receiver_zip
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.receiver_mobile
     *
     * @return the value of online_trade.receiver_mobile
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.receiver_mobile
     *
     * @param receiverMobile
     *            the value for online_trade.receiver_mobile
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.receiver_phone
     *
     * @return the value of online_trade.receiver_phone
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.receiver_phone
     *
     * @param receiverPhone
     *            the value for online_trade.receiver_phone
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.consign_time
     *
     * @return the value of online_trade.consign_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getConsignTime() {
        return consignTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.consign_time
     *
     * @param consignTime
     *            the value for online_trade.consign_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setConsignTime(String consignTime) {
        this.consignTime = consignTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.received_payment
     *
     * @return the value of online_trade.received_payment
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getReceivedPayment() {
        return receivedPayment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.received_payment
     *
     * @param receivedPayment
     *            the value for online_trade.received_payment
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setReceivedPayment(String receivedPayment) {
        this.receivedPayment = receivedPayment;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.receiver_country
     *
     * @return the value of online_trade.receiver_country
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getReceiverCountry() {
        return receiverCountry;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.receiver_country
     *
     * @param receiverCountry
     *            the value for online_trade.receiver_country
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setReceiverCountry(String receiverCountry) {
        this.receiverCountry = receiverCountry;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.receiver_town
     *
     * @return the value of online_trade.receiver_town
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getReceiverTown() {
        return receiverTown;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.receiver_town
     *
     * @param receiverTown
     *            the value for online_trade.receiver_town
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setReceiverTown(String receiverTown) {
        this.receiverTown = receiverTown;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.order_tax_fee
     *
     * @return the value of online_trade.order_tax_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getOrderTaxFee() {
        return orderTaxFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.order_tax_fee
     *
     * @param orderTaxFee
     *            the value for online_trade.order_tax_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setOrderTaxFee(String orderTaxFee) {
        this.orderTaxFee = orderTaxFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.shop_pick
     *
     * @return the value of online_trade.shop_pick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getShopPick() {
        return shopPick;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.shop_pick
     *
     * @param shopPick
     *            the value for online_trade.shop_pick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setShopPick(String shopPick) {
        this.shopPick = shopPick;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.tid
     *
     * @return the value of online_trade.tid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.tid
     *
     * @param tid
     *            the value for online_trade.tid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.num
     *
     * @return the value of online_trade.num
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.num
     *
     * @param num
     *            the value for online_trade.num
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.numIid
     *
     * @return the value of online_trade.numIid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Integer getNumiid() {
        return numiid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.numIid
     *
     * @param numiid
     *            the value for online_trade.numIid
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setNumiid(Integer numiid) {
        this.numiid = numiid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.status
     *
     * @return the value of online_trade.status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.status
     *
     * @param status
     *            the value for online_trade.status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.title
     *
     * @return the value of online_trade.title
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.title
     *
     * @param title
     *            the value for online_trade.title
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.type
     *
     * @return the value of online_trade.type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.type
     *
     * @param type
     *            the value for online_trade.type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.price
     *
     * @return the value of online_trade.price
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.price
     *
     * @param price
     *            the value for online_trade.price
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.discount_fee
     *
     * @return the value of online_trade.discount_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Double getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.discount_fee
     *
     * @param discountFee
     *            the value for online_trade.discount_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setDiscountFee(Double discountFee) {
        this.discountFee = discountFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.total_fee
     *
     * @return the value of online_trade.total_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Double getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.total_fee
     *
     * @param totalFee
     *            the value for online_trade.total_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.created
     *
     * @return the value of online_trade.created
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.created
     *
     * @param created
     *            the value for online_trade.created
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.pay_time
     *
     * @return the value of online_trade.pay_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.pay_time
     *
     * @param payTime
     *            the value for online_trade.pay_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.modified
     *
     * @return the value of online_trade.modified
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.modified
     *
     * @param modified
     *            the value for online_trade.modified
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.end_time
     *
     * @return the value of online_trade.end_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.end_time
     *
     * @param endTime
     *            the value for online_trade.end_time
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.seller_flag
     *
     * @return the value of online_trade.seller_flag
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getSellerFlag() {
        return sellerFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.seller_flag
     *
     * @param sellerFlag
     *            the value for online_trade.seller_flag
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setSellerFlag(String sellerFlag) {
        this.sellerFlag = sellerFlag;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.buyer_nick
     *
     * @return the value of online_trade.buyer_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.buyer_nick
     *
     * @param buyerNick
     *            the value for online_trade.buyer_nick
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.has_buyer_message
     *
     * @return the value of online_trade.has_buyer_message
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getHasBuyerMessage() {
        return hasBuyerMessage;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.has_buyer_message
     *
     * @param hasBuyerMessage
     *            the value for online_trade.has_buyer_message
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setHasBuyerMessage(String hasBuyerMessage) {
        this.hasBuyerMessage = hasBuyerMessage;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.credit_card_fee
     *
     * @return the value of online_trade.credit_card_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Double getCreditCardFee() {
        return creditCardFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.credit_card_fee
     *
     * @param creditCardFee
     *            the value for online_trade.credit_card_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setCreditCardFee(Double creditCardFee) {
        this.creditCardFee = creditCardFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.step_trade_status
     *
     * @return the value of online_trade.step_trade_status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getStepTradeStatus() {
        return stepTradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.step_trade_status
     *
     * @param stepTradeStatus
     *            the value for online_trade.step_trade_status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setStepTradeStatus(String stepTradeStatus) {
        this.stepTradeStatus = stepTradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.step_paid_fee
     *
     * @return the value of online_trade.step_paid_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Double getStepPaidFee() {
        return stepPaidFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.step_paid_fee
     *
     * @param stepPaidFee
     *            the value for online_trade.step_paid_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setStepPaidFee(Double stepPaidFee) {
        this.stepPaidFee = stepPaidFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.mark_desc
     *
     * @return the value of online_trade.mark_desc
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getMarkDesc() {
        return markDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.mark_desc
     *
     * @param markDesc
     *            the value for online_trade.mark_desc
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setMarkDesc(String markDesc) {
        this.markDesc = markDesc;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.shipping_type
     *
     * @return the value of online_trade.shipping_type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getShippingType() {
        return shippingType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.shipping_type
     *
     * @param shippingType
     *            the value for online_trade.shipping_type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setShippingType(String shippingType) {
        this.shippingType = shippingType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.adjust_fee
     *
     * @return the value of online_trade.adjust_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Double getAdjustFee() {
        return adjustFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.adjust_fee
     *
     * @param adjustFee
     *            the value for online_trade.adjust_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setAdjustFee(Double adjustFee) {
        this.adjustFee = adjustFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.trade_from
     *
     * @return the value of online_trade.trade_from
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getTradeFrom() {
        return tradeFrom;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.trade_from
     *
     * @param tradeFrom
     *            the value for online_trade.trade_from
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setTradeFrom(String tradeFrom) {
        this.tradeFrom = tradeFrom;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.buyer_rate
     *
     * @return the value of online_trade.buyer_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Boolean getBuyerRate() {
        return buyerRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.buyer_rate
     *
     * @param buyerRate
     *            the value for online_trade.buyer_rate
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setBuyerRate(Boolean buyerRate) {
        this.buyerRate = buyerRate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.receiver_city
     *
     * @return the value of online_trade.receiver_city
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.receiver_city
     *
     * @param receiverCity
     *            the value for online_trade.receiver_city
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.receiver_district
     *
     * @return the value of online_trade.receiver_district
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.receiver_district
     *
     * @param receiverDistrict
     *            the value for online_trade.receiver_district
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.o2o
     *
     * @return the value of online_trade.o2o
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getO2o() {
        return o2o;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.o2o
     *
     * @param o2o
     *            the value for online_trade.o2o
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setO2o(String o2o) {
        this.o2o = o2o;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.o2o_guide_id
     *
     * @return the value of online_trade.o2o_guide_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getO2oGuideId() {
        return o2oGuideId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.o2o_guide_id
     *
     * @param o2oGuideId
     *            the value for online_trade.o2o_guide_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setO2oGuideId(String o2oGuideId) {
        this.o2oGuideId = o2oGuideId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.o2o_shop_id
     *
     * @return the value of online_trade.o2o_shop_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getO2oShopId() {
        return o2oShopId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.o2o_shop_id
     *
     * @param o2oShopId
     *            the value for online_trade.o2o_shop_id
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setO2oShopId(String o2oShopId) {
        this.o2oShopId = o2oShopId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.o2o_guide_name
     *
     * @return the value of online_trade.o2o_guide_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getO2oGuideName() {
        return o2oGuideName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.o2o_guide_name
     *
     * @param o2oGuideName
     *            the value for online_trade.o2o_guide_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setO2oGuideName(String o2oGuideName) {
        this.o2oGuideName = o2oGuideName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.o2o_shop_name
     *
     * @return the value of online_trade.o2o_shop_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getO2oShopName() {
        return o2oShopName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.o2o_shop_name
     *
     * @param o2oShopName
     *            the value for online_trade.o2o_shop_name
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setO2oShopName(String o2oShopName) {
        this.o2oShopName = o2oShopName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.o2o_delivery
     *
     * @return the value of online_trade.o2o_delivery
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getO2oDelivery() {
        return o2oDelivery;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.o2o_delivery
     *
     * @param o2oDelivery
     *            the value for online_trade.o2o_delivery
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setO2oDelivery(String o2oDelivery) {
        this.o2oDelivery = o2oDelivery;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.rx_audit_status
     *
     * @return the value of online_trade.rx_audit_status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getRxAuditStatus() {
        return rxAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.rx_audit_status
     *
     * @param rxAuditStatus
     *            the value for online_trade.rx_audit_status
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setRxAuditStatus(String rxAuditStatus) {
        this.rxAuditStatus = rxAuditStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.post_gate_declare
     *
     * @return the value of online_trade.post_gate_declare
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Boolean getPostGateDeclare() {
        return postGateDeclare;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.post_gate_declare
     *
     * @param postGateDeclare
     *            the value for online_trade.post_gate_declare
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setPostGateDeclare(Boolean postGateDeclare) {
        this.postGateDeclare = postGateDeclare;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.cross_bonded_declare
     *
     * @return the value of online_trade.cross_bonded_declare
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public Boolean getCrossBondedDeclare() {
        return crossBondedDeclare;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.cross_bonded_declare
     *
     * @param crossBondedDeclare
     *            the value for online_trade.cross_bonded_declare
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setCrossBondedDeclare(Boolean crossBondedDeclare) {
        this.crossBondedDeclare = crossBondedDeclare;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.order_tax_promotion_fee
     *
     * @return the value of online_trade.order_tax_promotion_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getOrderTaxPromotionFee() {
        return orderTaxPromotionFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.order_tax_promotion_fee
     *
     * @param orderTaxPromotionFee
     *            the value for online_trade.order_tax_promotion_fee
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setOrderTaxPromotionFee(String orderTaxPromotionFee) {
        this.orderTaxPromotionFee = orderTaxPromotionFee;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column online_trade.service_type
     *
     * @return the value of online_trade.service_type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column online_trade.service_type
     *
     * @param serviceType
     *            the value for online_trade.service_type
     *
     * @mbg.generated Sun Mar 04 14:04:44 CST 2018
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }
}