package com.ycxy.wdgj.taobao.domain;

public class Role {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.id
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.sub_role_name
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    private String subRoleName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.role_name
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    private String roleName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.user_id
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    private Integer userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column role.role
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.id
     * @return  the value of role.id
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.id
     * @param id  the value for role.id
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.sub_role_name
     * @return  the value of role.sub_role_name
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    public String getSubRoleName() {
        return subRoleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.sub_role_name
     * @param subRoleName  the value for role.sub_role_name
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    public void setSubRoleName(String subRoleName) {
        this.subRoleName = subRoleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.role_name
     * @return  the value of role.role_name
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.role_name
     * @param roleName  the value for role.role_name
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.user_id
     * @return  the value of role.user_id
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.user_id
     * @param userId  the value for role.user_id
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column role.role
     * @return  the value of role.role
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column role.role
     * @param role  the value for role.role
     * @mbg.generated  Thu Mar 08 15:36:28 CST 2018
     */
    public void setRole(String role) {
        this.role = role;
    }
}