package com.ycxy.wdgj.model;

import javax.validation.constraints.NotNull;

import com.ycxy.wdgj.valid.insert;

public class Product {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.weight
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    @NotNull(groups = { insert.class })
    private Double weight;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.barcode
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    private String barcode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.image
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    private String image;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.price
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    @NotNull(groups = { insert.class })
    private Double price;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.goods_name
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    @NotNull(groups = { insert.class })
    private String goodsName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.goods_id
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    private String goodsId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column product.isDelete
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    private Byte isdelete;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
     * @return  the value of product.id
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
     * @param id  the value for product.id
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.weight
     * @return  the value of product.weight
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.weight
     * @param weight  the value for product.weight
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.barcode
     * @return  the value of product.barcode
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.barcode
     * @param barcode  the value for product.barcode
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.image
     * @return  the value of product.image
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.image
     * @param image  the value for product.image
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.price
     * @return  the value of product.price
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.price
     * @param price  the value for product.price
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.goods_name
     * @return  the value of product.goods_name
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.goods_name
     * @param goodsName  the value for product.goods_name
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.goods_id
     * @return  the value of product.goods_id
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.goods_id
     * @param goodsId  the value for product.goods_id
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column product.isDelete
     * @return  the value of product.isDelete
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column product.isDelete
     * @param isdelete  the value for product.isDelete
     * @mbg.generated  Thu Feb 22 15:11:18 CST 2018
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }
}