package com.ycxy.wdgj.model;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Shop {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * shop.id
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * shop.shop_name
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    private String shopName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * shop.shop_id
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    private Long shopId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * shop.last_download_time
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    private Date lastDownloadTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * shop.auth_code
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    private String authCode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * shop.gmt_create
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    private Date gmtCreate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * shop.gmt_modified
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    private Date gmtModified;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * shop.user_id
     * 
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column shop.id
     * 
     * @return the value of shop.id
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column shop.id
     * 
     * @param id
     *            the value for shop.id
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column shop.shop_name
     * 
     * @return the value of shop.shop_name
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column shop.shop_name
     * 
     * @param shopName
     *            the value for shop.shop_name
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column shop.shop_id
     * 
     * @return the value of shop.shop_id
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column shop.shop_id
     * 
     * @param shopId
     *            the value for shop.shop_id
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column shop.last_download_time
     * 
     * @return the value of shop.last_download_time
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public Date getLastDownloadTime() {
        return lastDownloadTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column shop.last_download_time
     * 
     * @param lastDownloadTime
     *            the value for shop.last_download_time
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public void setLastDownloadTime(Date lastDownloadTime) {
        this.lastDownloadTime = lastDownloadTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column shop.auth_code
     * 
     * @return the value of shop.auth_code
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column shop.auth_code
     * 
     * @param authCode
     *            the value for shop.auth_code
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column shop.gmt_create
     * 
     * @return the value of shop.gmt_create
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column shop.gmt_create
     * 
     * @param gmtCreate
     *            the value for shop.gmt_create
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column shop.gmt_modified
     * 
     * @return the value of shop.gmt_modified
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column shop.gmt_modified
     * 
     * @param gmtModified
     *            the value for shop.gmt_modified
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column shop.user_id
     * 
     * @return the value of shop.user_id
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column shop.user_id
     * 
     * @param userId
     *            the value for shop.user_id
     * @mbg.generated Fri Feb 23 16:47:14 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}