package com.ycxy.wdgj.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TradeOrderExample {
	protected String limitByClause;
	
    public String getLimitByClause() {
		return limitByClause;
	}

	public void setLimitByClause(String limitByClause) {
		this.limitByClause = limitByClause;
	}

	public void setOredCriteria(List<Criteria> oredCriteria) {
		this.oredCriteria = oredCriteria;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	public TradeOrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNull() {
			addCriterion("pay_time is null");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNotNull() {
			addCriterion("pay_time is not null");
			return (Criteria) this;
		}

		public Criteria andPayTimeEqualTo(Date value) {
			addCriterion("pay_time =", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotEqualTo(Date value) {
			addCriterion("pay_time <>", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThan(Date value) {
			addCriterion("pay_time >", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("pay_time >=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThan(Date value) {
			addCriterion("pay_time <", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThanOrEqualTo(Date value) {
			addCriterion("pay_time <=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeIn(List<Date> values) {
			addCriterion("pay_time in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotIn(List<Date> values) {
			addCriterion("pay_time not in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeBetween(Date value1, Date value2) {
			addCriterion("pay_time between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotBetween(Date value1, Date value2) {
			addCriterion("pay_time not between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeIsNull() {
			addCriterion("logisticsCode is null");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeIsNotNull() {
			addCriterion("logisticsCode is not null");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeEqualTo(String value) {
			addCriterion("logisticsCode =", value, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeNotEqualTo(String value) {
			addCriterion("logisticsCode <>", value, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeGreaterThan(String value) {
			addCriterion("logisticsCode >", value, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeGreaterThanOrEqualTo(String value) {
			addCriterion("logisticsCode >=", value, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeLessThan(String value) {
			addCriterion("logisticsCode <", value, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeLessThanOrEqualTo(String value) {
			addCriterion("logisticsCode <=", value, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeLike(String value) {
			addCriterion("logisticsCode like", value, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeNotLike(String value) {
			addCriterion("logisticsCode not like", value, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeIn(List<String> values) {
			addCriterion("logisticsCode in", values, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeNotIn(List<String> values) {
			addCriterion("logisticsCode not in", values, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeBetween(String value1, String value2) {
			addCriterion("logisticsCode between", value1, value2, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticscodeNotBetween(String value1, String value2) {
			addCriterion("logisticsCode not between", value1, value2, "logisticscode");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameIsNull() {
			addCriterion("logisticsName is null");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameIsNotNull() {
			addCriterion("logisticsName is not null");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameEqualTo(String value) {
			addCriterion("logisticsName =", value, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameNotEqualTo(String value) {
			addCriterion("logisticsName <>", value, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameGreaterThan(String value) {
			addCriterion("logisticsName >", value, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameGreaterThanOrEqualTo(String value) {
			addCriterion("logisticsName >=", value, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameLessThan(String value) {
			addCriterion("logisticsName <", value, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameLessThanOrEqualTo(String value) {
			addCriterion("logisticsName <=", value, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameLike(String value) {
			addCriterion("logisticsName like", value, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameNotLike(String value) {
			addCriterion("logisticsName not like", value, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameIn(List<String> values) {
			addCriterion("logisticsName in", values, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameNotIn(List<String> values) {
			addCriterion("logisticsName not in", values, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameBetween(String value1, String value2) {
			addCriterion("logisticsName between", value1, value2, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsnameNotBetween(String value1, String value2) {
			addCriterion("logisticsName not between", value1, value2, "logisticsname");
			return (Criteria) this;
		}

		public Criteria andLogisticsidIsNull() {
			addCriterion("logisticsId is null");
			return (Criteria) this;
		}

		public Criteria andLogisticsidIsNotNull() {
			addCriterion("logisticsId is not null");
			return (Criteria) this;
		}

		public Criteria andLogisticsidEqualTo(String value) {
			addCriterion("logisticsId =", value, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andLogisticsidNotEqualTo(String value) {
			addCriterion("logisticsId <>", value, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andLogisticsidGreaterThan(String value) {
			addCriterion("logisticsId >", value, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andLogisticsidGreaterThanOrEqualTo(String value) {
			addCriterion("logisticsId >=", value, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andLogisticsidLessThan(String value) {
			addCriterion("logisticsId <", value, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andLogisticsidLessThanOrEqualTo(String value) {
			addCriterion("logisticsId <=", value, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andLogisticsidLike(String value) {
			addCriterion("logisticsId like", value, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andLogisticsidNotLike(String value) {
			addCriterion("logisticsId not like", value, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andLogisticsidIn(List<String> values) {
			addCriterion("logisticsId in", values, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andLogisticsidNotIn(List<String> values) {
			addCriterion("logisticsId not in", values, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andLogisticsidBetween(String value1, String value2) {
			addCriterion("logisticsId between", value1, value2, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andLogisticsidNotBetween(String value1, String value2) {
			addCriterion("logisticsId not between", value1, value2, "logisticsid");
			return (Criteria) this;
		}

		public Criteria andTradeIdIsNull() {
			addCriterion("trade_id is null");
			return (Criteria) this;
		}

		public Criteria andTradeIdIsNotNull() {
			addCriterion("trade_id is not null");
			return (Criteria) this;
		}

		public Criteria andTradeIdEqualTo(Long value) {
			addCriterion("trade_id =", value, "tradeId");
			return (Criteria) this;
		}

		public Criteria andTradeIdNotEqualTo(Long value) {
			addCriterion("trade_id <>", value, "tradeId");
			return (Criteria) this;
		}

		public Criteria andTradeIdGreaterThan(Long value) {
			addCriterion("trade_id >", value, "tradeId");
			return (Criteria) this;
		}

		public Criteria andTradeIdGreaterThanOrEqualTo(Long value) {
			addCriterion("trade_id >=", value, "tradeId");
			return (Criteria) this;
		}

		public Criteria andTradeIdLessThan(Long value) {
			addCriterion("trade_id <", value, "tradeId");
			return (Criteria) this;
		}

		public Criteria andTradeIdLessThanOrEqualTo(Long value) {
			addCriterion("trade_id <=", value, "tradeId");
			return (Criteria) this;
		}

		public Criteria andTradeIdIn(List<Long> values) {
			addCriterion("trade_id in", values, "tradeId");
			return (Criteria) this;
		}

		public Criteria andTradeIdNotIn(List<Long> values) {
			addCriterion("trade_id not in", values, "tradeId");
			return (Criteria) this;
		}

		public Criteria andTradeIdBetween(Long value1, Long value2) {
			addCriterion("trade_id between", value1, value2, "tradeId");
			return (Criteria) this;
		}

		public Criteria andTradeIdNotBetween(Long value1, Long value2) {
			addCriterion("trade_id not between", value1, value2, "tradeId");
			return (Criteria) this;
		}

		public Criteria andTradeNoIsNull() {
			addCriterion("trade_no is null");
			return (Criteria) this;
		}

		public Criteria andTradeNoIsNotNull() {
			addCriterion("trade_no is not null");
			return (Criteria) this;
		}

		public Criteria andTradeNoEqualTo(Long value) {
			addCriterion("trade_no =", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoNotEqualTo(Long value) {
			addCriterion("trade_no <>", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoGreaterThan(Long value) {
			addCriterion("trade_no >", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoGreaterThanOrEqualTo(Long value) {
			addCriterion("trade_no >=", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoLessThan(Long value) {
			addCriterion("trade_no <", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoLessThanOrEqualTo(Long value) {
			addCriterion("trade_no <=", value, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoIn(List<Long> values) {
			addCriterion("trade_no in", values, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoNotIn(List<Long> values) {
			addCriterion("trade_no not in", values, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoBetween(Long value1, Long value2) {
			addCriterion("trade_no between", value1, value2, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andTradeNoNotBetween(Long value1, Long value2) {
			addCriterion("trade_no not between", value1, value2, "tradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdIsNull() {
			addCriterion("source_trade_id is null");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdIsNotNull() {
			addCriterion("source_trade_id is not null");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdEqualTo(String value) {
			addCriterion("source_trade_id =", value, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdNotEqualTo(String value) {
			addCriterion("source_trade_id <>", value, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdGreaterThan(String value) {
			addCriterion("source_trade_id >", value, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdGreaterThanOrEqualTo(String value) {
			addCriterion("source_trade_id >=", value, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdLessThan(String value) {
			addCriterion("source_trade_id <", value, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdLessThanOrEqualTo(String value) {
			addCriterion("source_trade_id <=", value, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdLike(String value) {
			addCriterion("source_trade_id like", value, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdNotLike(String value) {
			addCriterion("source_trade_id not like", value, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdIn(List<String> values) {
			addCriterion("source_trade_id in", values, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdNotIn(List<String> values) {
			addCriterion("source_trade_id not in", values, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdBetween(String value1, String value2) {
			addCriterion("source_trade_id between", value1, value2, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeIdNotBetween(String value1, String value2) {
			addCriterion("source_trade_id not between", value1, value2, "sourceTradeId");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoIsNull() {
			addCriterion("source_trade_no is null");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoIsNotNull() {
			addCriterion("source_trade_no is not null");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoEqualTo(String value) {
			addCriterion("source_trade_no =", value, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoNotEqualTo(String value) {
			addCriterion("source_trade_no <>", value, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoGreaterThan(String value) {
			addCriterion("source_trade_no >", value, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoGreaterThanOrEqualTo(String value) {
			addCriterion("source_trade_no >=", value, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoLessThan(String value) {
			addCriterion("source_trade_no <", value, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoLessThanOrEqualTo(String value) {
			addCriterion("source_trade_no <=", value, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoLike(String value) {
			addCriterion("source_trade_no like", value, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoNotLike(String value) {
			addCriterion("source_trade_no not like", value, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoIn(List<String> values) {
			addCriterion("source_trade_no in", values, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoNotIn(List<String> values) {
			addCriterion("source_trade_no not in", values, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoBetween(String value1, String value2) {
			addCriterion("source_trade_no between", value1, value2, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andSourceTradeNoNotBetween(String value1, String value2) {
			addCriterion("source_trade_no not between", value1, value2, "sourceTradeNo");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNull() {
			addCriterion("shop_id is null");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNotNull() {
			addCriterion("shop_id is not null");
			return (Criteria) this;
		}

		public Criteria andShopIdEqualTo(Long value) {
			addCriterion("shop_id =", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotEqualTo(Long value) {
			addCriterion("shop_id <>", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThan(Long value) {
			addCriterion("shop_id >", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThanOrEqualTo(Long value) {
			addCriterion("shop_id >=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThan(Long value) {
			addCriterion("shop_id <", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThanOrEqualTo(Long value) {
			addCriterion("shop_id <=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdIn(List<Long> values) {
			addCriterion("shop_id in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotIn(List<Long> values) {
			addCriterion("shop_id not in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdBetween(Long value1, Long value2) {
			addCriterion("shop_id between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotBetween(Long value1, Long value2) {
			addCriterion("shop_id not between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNull() {
			addCriterion("shop_name is null");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNotNull() {
			addCriterion("shop_name is not null");
			return (Criteria) this;
		}

		public Criteria andShopNameEqualTo(String value) {
			addCriterion("shop_name =", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotEqualTo(String value) {
			addCriterion("shop_name <>", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThan(String value) {
			addCriterion("shop_name >", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThanOrEqualTo(String value) {
			addCriterion("shop_name >=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThan(String value) {
			addCriterion("shop_name <", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThanOrEqualTo(String value) {
			addCriterion("shop_name <=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLike(String value) {
			addCriterion("shop_name like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotLike(String value) {
			addCriterion("shop_name not like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameIn(List<String> values) {
			addCriterion("shop_name in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotIn(List<String> values) {
			addCriterion("shop_name not in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameBetween(String value1, String value2) {
			addCriterion("shop_name between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotBetween(String value1, String value2) {
			addCriterion("shop_name not between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andSellerIsNull() {
			addCriterion("seller is null");
			return (Criteria) this;
		}

		public Criteria andSellerIsNotNull() {
			addCriterion("seller is not null");
			return (Criteria) this;
		}

		public Criteria andSellerEqualTo(String value) {
			addCriterion("seller =", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerNotEqualTo(String value) {
			addCriterion("seller <>", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerGreaterThan(String value) {
			addCriterion("seller >", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerGreaterThanOrEqualTo(String value) {
			addCriterion("seller >=", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerLessThan(String value) {
			addCriterion("seller <", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerLessThanOrEqualTo(String value) {
			addCriterion("seller <=", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerLike(String value) {
			addCriterion("seller like", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerNotLike(String value) {
			addCriterion("seller not like", value, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerIn(List<String> values) {
			addCriterion("seller in", values, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerNotIn(List<String> values) {
			addCriterion("seller not in", values, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerBetween(String value1, String value2) {
			addCriterion("seller between", value1, value2, "seller");
			return (Criteria) this;
		}

		public Criteria andSellerNotBetween(String value1, String value2) {
			addCriterion("seller not between", value1, value2, "seller");
			return (Criteria) this;
		}

		public Criteria andTradeTypeIsNull() {
			addCriterion("trade_type is null");
			return (Criteria) this;
		}

		public Criteria andTradeTypeIsNotNull() {
			addCriterion("trade_type is not null");
			return (Criteria) this;
		}

		public Criteria andTradeTypeEqualTo(Byte value) {
			addCriterion("trade_type =", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeNotEqualTo(Byte value) {
			addCriterion("trade_type <>", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeGreaterThan(Byte value) {
			addCriterion("trade_type >", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("trade_type >=", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeLessThan(Byte value) {
			addCriterion("trade_type <", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeLessThanOrEqualTo(Byte value) {
			addCriterion("trade_type <=", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeIn(List<Byte> values) {
			addCriterion("trade_type in", values, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeNotIn(List<Byte> values) {
			addCriterion("trade_type not in", values, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeBetween(Byte value1, Byte value2) {
			addCriterion("trade_type between", value1, value2, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("trade_type not between", value1, value2, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyIsNull() {
			addCriterion("total_money is null");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyIsNotNull() {
			addCriterion("total_money is not null");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyEqualTo(Double value) {
			addCriterion("total_money =", value, "totalMoney");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyNotEqualTo(Double value) {
			addCriterion("total_money <>", value, "totalMoney");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyGreaterThan(Double value) {
			addCriterion("total_money >", value, "totalMoney");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyGreaterThanOrEqualTo(Double value) {
			addCriterion("total_money >=", value, "totalMoney");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyLessThan(Double value) {
			addCriterion("total_money <", value, "totalMoney");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyLessThanOrEqualTo(Double value) {
			addCriterion("total_money <=", value, "totalMoney");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyIn(List<Double> values) {
			addCriterion("total_money in", values, "totalMoney");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyNotIn(List<Double> values) {
			addCriterion("total_money not in", values, "totalMoney");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyBetween(Double value1, Double value2) {
			addCriterion("total_money between", value1, value2, "totalMoney");
			return (Criteria) this;
		}

		public Criteria andTotalMoneyNotBetween(Double value1, Double value2) {
			addCriterion("total_money not between", value1, value2, "totalMoney");
			return (Criteria) this;
		}

		public Criteria andSellerMemoIsNull() {
			addCriterion("seller_memo is null");
			return (Criteria) this;
		}

		public Criteria andSellerMemoIsNotNull() {
			addCriterion("seller_memo is not null");
			return (Criteria) this;
		}

		public Criteria andSellerMemoEqualTo(String value) {
			addCriterion("seller_memo =", value, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andSellerMemoNotEqualTo(String value) {
			addCriterion("seller_memo <>", value, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andSellerMemoGreaterThan(String value) {
			addCriterion("seller_memo >", value, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andSellerMemoGreaterThanOrEqualTo(String value) {
			addCriterion("seller_memo >=", value, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andSellerMemoLessThan(String value) {
			addCriterion("seller_memo <", value, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andSellerMemoLessThanOrEqualTo(String value) {
			addCriterion("seller_memo <=", value, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andSellerMemoLike(String value) {
			addCriterion("seller_memo like", value, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andSellerMemoNotLike(String value) {
			addCriterion("seller_memo not like", value, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andSellerMemoIn(List<String> values) {
			addCriterion("seller_memo in", values, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andSellerMemoNotIn(List<String> values) {
			addCriterion("seller_memo not in", values, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andSellerMemoBetween(String value1, String value2) {
			addCriterion("seller_memo between", value1, value2, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andSellerMemoNotBetween(String value1, String value2) {
			addCriterion("seller_memo not between", value1, value2, "sellerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoIsNull() {
			addCriterion("buyer_memo is null");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoIsNotNull() {
			addCriterion("buyer_memo is not null");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoEqualTo(String value) {
			addCriterion("buyer_memo =", value, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoNotEqualTo(String value) {
			addCriterion("buyer_memo <>", value, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoGreaterThan(String value) {
			addCriterion("buyer_memo >", value, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoGreaterThanOrEqualTo(String value) {
			addCriterion("buyer_memo >=", value, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoLessThan(String value) {
			addCriterion("buyer_memo <", value, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoLessThanOrEqualTo(String value) {
			addCriterion("buyer_memo <=", value, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoLike(String value) {
			addCriterion("buyer_memo like", value, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoNotLike(String value) {
			addCriterion("buyer_memo not like", value, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoIn(List<String> values) {
			addCriterion("buyer_memo in", values, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoNotIn(List<String> values) {
			addCriterion("buyer_memo not in", values, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoBetween(String value1, String value2) {
			addCriterion("buyer_memo between", value1, value2, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andBuyerMemoNotBetween(String value1, String value2) {
			addCriterion("buyer_memo not between", value1, value2, "buyerMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoIsNull() {
			addCriterion("append_memo is null");
			return (Criteria) this;
		}

		public Criteria andAppendMemoIsNotNull() {
			addCriterion("append_memo is not null");
			return (Criteria) this;
		}

		public Criteria andAppendMemoEqualTo(String value) {
			addCriterion("append_memo =", value, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoNotEqualTo(String value) {
			addCriterion("append_memo <>", value, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoGreaterThan(String value) {
			addCriterion("append_memo >", value, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoGreaterThanOrEqualTo(String value) {
			addCriterion("append_memo >=", value, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoLessThan(String value) {
			addCriterion("append_memo <", value, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoLessThanOrEqualTo(String value) {
			addCriterion("append_memo <=", value, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoLike(String value) {
			addCriterion("append_memo like", value, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoNotLike(String value) {
			addCriterion("append_memo not like", value, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoIn(List<String> values) {
			addCriterion("append_memo in", values, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoNotIn(List<String> values) {
			addCriterion("append_memo not in", values, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoBetween(String value1, String value2) {
			addCriterion("append_memo between", value1, value2, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andAppendMemoNotBetween(String value1, String value2) {
			addCriterion("append_memo not between", value1, value2, "appendMemo");
			return (Criteria) this;
		}

		public Criteria andPaymentIsNull() {
			addCriterion("payment is null");
			return (Criteria) this;
		}

		public Criteria andPaymentIsNotNull() {
			addCriterion("payment is not null");
			return (Criteria) this;
		}

		public Criteria andPaymentEqualTo(Double value) {
			addCriterion("payment =", value, "payment");
			return (Criteria) this;
		}

		public Criteria andPaymentNotEqualTo(Double value) {
			addCriterion("payment <>", value, "payment");
			return (Criteria) this;
		}

		public Criteria andPaymentGreaterThan(Double value) {
			addCriterion("payment >", value, "payment");
			return (Criteria) this;
		}

		public Criteria andPaymentGreaterThanOrEqualTo(Double value) {
			addCriterion("payment >=", value, "payment");
			return (Criteria) this;
		}

		public Criteria andPaymentLessThan(Double value) {
			addCriterion("payment <", value, "payment");
			return (Criteria) this;
		}

		public Criteria andPaymentLessThanOrEqualTo(Double value) {
			addCriterion("payment <=", value, "payment");
			return (Criteria) this;
		}

		public Criteria andPaymentIn(List<Double> values) {
			addCriterion("payment in", values, "payment");
			return (Criteria) this;
		}

		public Criteria andPaymentNotIn(List<Double> values) {
			addCriterion("payment not in", values, "payment");
			return (Criteria) this;
		}

		public Criteria andPaymentBetween(Double value1, Double value2) {
			addCriterion("payment between", value1, value2, "payment");
			return (Criteria) this;
		}

		public Criteria andPaymentNotBetween(Double value1, Double value2) {
			addCriterion("payment not between", value1, value2, "payment");
			return (Criteria) this;
		}

		public Criteria andTaxFeeIsNull() {
			addCriterion("tax_fee is null");
			return (Criteria) this;
		}

		public Criteria andTaxFeeIsNotNull() {
			addCriterion("tax_fee is not null");
			return (Criteria) this;
		}

		public Criteria andTaxFeeEqualTo(Double value) {
			addCriterion("tax_fee =", value, "taxFee");
			return (Criteria) this;
		}

		public Criteria andTaxFeeNotEqualTo(Double value) {
			addCriterion("tax_fee <>", value, "taxFee");
			return (Criteria) this;
		}

		public Criteria andTaxFeeGreaterThan(Double value) {
			addCriterion("tax_fee >", value, "taxFee");
			return (Criteria) this;
		}

		public Criteria andTaxFeeGreaterThanOrEqualTo(Double value) {
			addCriterion("tax_fee >=", value, "taxFee");
			return (Criteria) this;
		}

		public Criteria andTaxFeeLessThan(Double value) {
			addCriterion("tax_fee <", value, "taxFee");
			return (Criteria) this;
		}

		public Criteria andTaxFeeLessThanOrEqualTo(Double value) {
			addCriterion("tax_fee <=", value, "taxFee");
			return (Criteria) this;
		}

		public Criteria andTaxFeeIn(List<Double> values) {
			addCriterion("tax_fee in", values, "taxFee");
			return (Criteria) this;
		}

		public Criteria andTaxFeeNotIn(List<Double> values) {
			addCriterion("tax_fee not in", values, "taxFee");
			return (Criteria) this;
		}

		public Criteria andTaxFeeBetween(Double value1, Double value2) {
			addCriterion("tax_fee between", value1, value2, "taxFee");
			return (Criteria) this;
		}

		public Criteria andTaxFeeNotBetween(Double value1, Double value2) {
			addCriterion("tax_fee not between", value1, value2, "taxFee");
			return (Criteria) this;
		}

		public Criteria andPostFeeIsNull() {
			addCriterion("post_fee is null");
			return (Criteria) this;
		}

		public Criteria andPostFeeIsNotNull() {
			addCriterion("post_fee is not null");
			return (Criteria) this;
		}

		public Criteria andPostFeeEqualTo(Double value) {
			addCriterion("post_fee =", value, "postFee");
			return (Criteria) this;
		}

		public Criteria andPostFeeNotEqualTo(Double value) {
			addCriterion("post_fee <>", value, "postFee");
			return (Criteria) this;
		}

		public Criteria andPostFeeGreaterThan(Double value) {
			addCriterion("post_fee >", value, "postFee");
			return (Criteria) this;
		}

		public Criteria andPostFeeGreaterThanOrEqualTo(Double value) {
			addCriterion("post_fee >=", value, "postFee");
			return (Criteria) this;
		}

		public Criteria andPostFeeLessThan(Double value) {
			addCriterion("post_fee <", value, "postFee");
			return (Criteria) this;
		}

		public Criteria andPostFeeLessThanOrEqualTo(Double value) {
			addCriterion("post_fee <=", value, "postFee");
			return (Criteria) this;
		}

		public Criteria andPostFeeIn(List<Double> values) {
			addCriterion("post_fee in", values, "postFee");
			return (Criteria) this;
		}

		public Criteria andPostFeeNotIn(List<Double> values) {
			addCriterion("post_fee not in", values, "postFee");
			return (Criteria) this;
		}

		public Criteria andPostFeeBetween(Double value1, Double value2) {
			addCriterion("post_fee between", value1, value2, "postFee");
			return (Criteria) this;
		}

		public Criteria andPostFeeNotBetween(Double value1, Double value2) {
			addCriterion("post_fee not between", value1, value2, "postFee");
			return (Criteria) this;
		}

		public Criteria andRegisterIsNull() {
			addCriterion("register is null");
			return (Criteria) this;
		}

		public Criteria andRegisterIsNotNull() {
			addCriterion("register is not null");
			return (Criteria) this;
		}

		public Criteria andRegisterEqualTo(String value) {
			addCriterion("register =", value, "register");
			return (Criteria) this;
		}

		public Criteria andRegisterNotEqualTo(String value) {
			addCriterion("register <>", value, "register");
			return (Criteria) this;
		}

		public Criteria andRegisterGreaterThan(String value) {
			addCriterion("register >", value, "register");
			return (Criteria) this;
		}

		public Criteria andRegisterGreaterThanOrEqualTo(String value) {
			addCriterion("register >=", value, "register");
			return (Criteria) this;
		}

		public Criteria andRegisterLessThan(String value) {
			addCriterion("register <", value, "register");
			return (Criteria) this;
		}

		public Criteria andRegisterLessThanOrEqualTo(String value) {
			addCriterion("register <=", value, "register");
			return (Criteria) this;
		}

		public Criteria andRegisterLike(String value) {
			addCriterion("register like", value, "register");
			return (Criteria) this;
		}

		public Criteria andRegisterNotLike(String value) {
			addCriterion("register not like", value, "register");
			return (Criteria) this;
		}

		public Criteria andRegisterIn(List<String> values) {
			addCriterion("register in", values, "register");
			return (Criteria) this;
		}

		public Criteria andRegisterNotIn(List<String> values) {
			addCriterion("register not in", values, "register");
			return (Criteria) this;
		}

		public Criteria andRegisterBetween(String value1, String value2) {
			addCriterion("register between", value1, value2, "register");
			return (Criteria) this;
		}

		public Criteria andRegisterNotBetween(String value1, String value2) {
			addCriterion("register not between", value1, value2, "register");
			return (Criteria) this;
		}

		public Criteria andAuditorIsNull() {
			addCriterion("auditor is null");
			return (Criteria) this;
		}

		public Criteria andAuditorIsNotNull() {
			addCriterion("auditor is not null");
			return (Criteria) this;
		}

		public Criteria andAuditorEqualTo(String value) {
			addCriterion("auditor =", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotEqualTo(String value) {
			addCriterion("auditor <>", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorGreaterThan(String value) {
			addCriterion("auditor >", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorGreaterThanOrEqualTo(String value) {
			addCriterion("auditor >=", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorLessThan(String value) {
			addCriterion("auditor <", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorLessThanOrEqualTo(String value) {
			addCriterion("auditor <=", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorLike(String value) {
			addCriterion("auditor like", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotLike(String value) {
			addCriterion("auditor not like", value, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorIn(List<String> values) {
			addCriterion("auditor in", values, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotIn(List<String> values) {
			addCriterion("auditor not in", values, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorBetween(String value1, String value2) {
			addCriterion("auditor between", value1, value2, "auditor");
			return (Criteria) this;
		}

		public Criteria andAuditorNotBetween(String value1, String value2) {
			addCriterion("auditor not between", value1, value2, "auditor");
			return (Criteria) this;
		}

		public Criteria andReviewerIsNull() {
			addCriterion("reviewer is null");
			return (Criteria) this;
		}

		public Criteria andReviewerIsNotNull() {
			addCriterion("reviewer is not null");
			return (Criteria) this;
		}

		public Criteria andReviewerEqualTo(String value) {
			addCriterion("reviewer =", value, "reviewer");
			return (Criteria) this;
		}

		public Criteria andReviewerNotEqualTo(String value) {
			addCriterion("reviewer <>", value, "reviewer");
			return (Criteria) this;
		}

		public Criteria andReviewerGreaterThan(String value) {
			addCriterion("reviewer >", value, "reviewer");
			return (Criteria) this;
		}

		public Criteria andReviewerGreaterThanOrEqualTo(String value) {
			addCriterion("reviewer >=", value, "reviewer");
			return (Criteria) this;
		}

		public Criteria andReviewerLessThan(String value) {
			addCriterion("reviewer <", value, "reviewer");
			return (Criteria) this;
		}

		public Criteria andReviewerLessThanOrEqualTo(String value) {
			addCriterion("reviewer <=", value, "reviewer");
			return (Criteria) this;
		}

		public Criteria andReviewerLike(String value) {
			addCriterion("reviewer like", value, "reviewer");
			return (Criteria) this;
		}

		public Criteria andReviewerNotLike(String value) {
			addCriterion("reviewer not like", value, "reviewer");
			return (Criteria) this;
		}

		public Criteria andReviewerIn(List<String> values) {
			addCriterion("reviewer in", values, "reviewer");
			return (Criteria) this;
		}

		public Criteria andReviewerNotIn(List<String> values) {
			addCriterion("reviewer not in", values, "reviewer");
			return (Criteria) this;
		}

		public Criteria andReviewerBetween(String value1, String value2) {
			addCriterion("reviewer between", value1, value2, "reviewer");
			return (Criteria) this;
		}

		public Criteria andReviewerNotBetween(String value1, String value2) {
			addCriterion("reviewer not between", value1, value2, "reviewer");
			return (Criteria) this;
		}

		public Criteria andIsDeleteIsNull() {
			addCriterion("is_delete is null");
			return (Criteria) this;
		}

		public Criteria andIsDeleteIsNotNull() {
			addCriterion("is_delete is not null");
			return (Criteria) this;
		}

		public Criteria andIsDeleteEqualTo(Byte value) {
			addCriterion("is_delete =", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteNotEqualTo(Byte value) {
			addCriterion("is_delete <>", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteGreaterThan(Byte value) {
			addCriterion("is_delete >", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteGreaterThanOrEqualTo(Byte value) {
			addCriterion("is_delete >=", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteLessThan(Byte value) {
			addCriterion("is_delete <", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteLessThanOrEqualTo(Byte value) {
			addCriterion("is_delete <=", value, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteIn(List<Byte> values) {
			addCriterion("is_delete in", values, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteNotIn(List<Byte> values) {
			addCriterion("is_delete not in", values, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteBetween(Byte value1, Byte value2) {
			addCriterion("is_delete between", value1, value2, "isDelete");
			return (Criteria) this;
		}

		public Criteria andIsDeleteNotBetween(Byte value1, Byte value2) {
			addCriterion("is_delete not between", value1, value2, "isDelete");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIsNull() {
			addCriterion("gmt_create is null");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIsNotNull() {
			addCriterion("gmt_create is not null");
			return (Criteria) this;
		}

		public Criteria andGmtCreateEqualTo(Date value) {
			addCriterion("gmt_create =", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotEqualTo(Date value) {
			addCriterion("gmt_create <>", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateGreaterThan(Date value) {
			addCriterion("gmt_create >", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
			addCriterion("gmt_create >=", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateLessThan(Date value) {
			addCriterion("gmt_create <", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
			addCriterion("gmt_create <=", value, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateIn(List<Date> values) {
			addCriterion("gmt_create in", values, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotIn(List<Date> values) {
			addCriterion("gmt_create not in", values, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateBetween(Date value1, Date value2) {
			addCriterion("gmt_create between", value1, value2, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
			addCriterion("gmt_create not between", value1, value2, "gmtCreate");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedIsNull() {
			addCriterion("gmt_modified is null");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedIsNotNull() {
			addCriterion("gmt_modified is not null");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedEqualTo(Date value) {
			addCriterion("gmt_modified =", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedNotEqualTo(Date value) {
			addCriterion("gmt_modified <>", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedGreaterThan(Date value) {
			addCriterion("gmt_modified >", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
			addCriterion("gmt_modified >=", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedLessThan(Date value) {
			addCriterion("gmt_modified <", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
			addCriterion("gmt_modified <=", value, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedIn(List<Date> values) {
			addCriterion("gmt_modified in", values, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedNotIn(List<Date> values) {
			addCriterion("gmt_modified not in", values, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedBetween(Date value1, Date value2) {
			addCriterion("gmt_modified between", value1, value2, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
			addCriterion("gmt_modified not between", value1, value2, "gmtModified");
			return (Criteria) this;
		}

		public Criteria andTradeStatusIsNull() {
			addCriterion("trade_status is null");
			return (Criteria) this;
		}

		public Criteria andTradeStatusIsNotNull() {
			addCriterion("trade_status is not null");
			return (Criteria) this;
		}

		public Criteria andTradeStatusEqualTo(Byte value) {
			addCriterion("trade_status =", value, "tradeStatus");
			return (Criteria) this;
		}

		public Criteria andTradeStatusNotEqualTo(Byte value) {
			addCriterion("trade_status <>", value, "tradeStatus");
			return (Criteria) this;
		}

		public Criteria andTradeStatusGreaterThan(Byte value) {
			addCriterion("trade_status >", value, "tradeStatus");
			return (Criteria) this;
		}

		public Criteria andTradeStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("trade_status >=", value, "tradeStatus");
			return (Criteria) this;
		}

		public Criteria andTradeStatusLessThan(Byte value) {
			addCriterion("trade_status <", value, "tradeStatus");
			return (Criteria) this;
		}

		public Criteria andTradeStatusLessThanOrEqualTo(Byte value) {
			addCriterion("trade_status <=", value, "tradeStatus");
			return (Criteria) this;
		}

		public Criteria andTradeStatusIn(List<Byte> values) {
			addCriterion("trade_status in", values, "tradeStatus");
			return (Criteria) this;
		}

		public Criteria andTradeStatusNotIn(List<Byte> values) {
			addCriterion("trade_status not in", values, "tradeStatus");
			return (Criteria) this;
		}

		public Criteria andTradeStatusBetween(Byte value1, Byte value2) {
			addCriterion("trade_status between", value1, value2, "tradeStatus");
			return (Criteria) this;
		}

		public Criteria andTradeStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("trade_status not between", value1, value2, "tradeStatus");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table trade_order
	 * @mbg.generated  Tue Apr 03 21:04:41 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_order
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 03 20:58:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}