package com.ycxy.wdgj.model;

import java.util.Date;

public class TradeReceiver {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.id
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.receiver_name
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private String receiverName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.receiver_phone
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private String receiverPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.country
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.state
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.city
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.district
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private String district;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.address
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.identity_card_type
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private Byte identityCardType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.identity_card_no
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private String identityCardNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.gmt_created
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private Date gmtCreated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.gmt_modified
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private Date gmtModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_receiver.trade_id
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	private Long tradeId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.id
	 * @return  the value of trade_receiver.id
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.id
	 * @param id  the value for trade_receiver.id
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.receiver_name
	 * @return  the value of trade_receiver.receiver_name
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public String getReceiverName() {
		return receiverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.receiver_name
	 * @param receiverName  the value for trade_receiver.receiver_name
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.receiver_phone
	 * @return  the value of trade_receiver.receiver_phone
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public String getReceiverPhone() {
		return receiverPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.receiver_phone
	 * @param receiverPhone  the value for trade_receiver.receiver_phone
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setReceiverPhone(String receiverPhone) {
		this.receiverPhone = receiverPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.country
	 * @return  the value of trade_receiver.country
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.country
	 * @param country  the value for trade_receiver.country
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.state
	 * @return  the value of trade_receiver.state
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.state
	 * @param state  the value for trade_receiver.state
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.city
	 * @return  the value of trade_receiver.city
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.city
	 * @param city  the value for trade_receiver.city
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.district
	 * @return  the value of trade_receiver.district
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public String getDistrict() {
		return district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.district
	 * @param district  the value for trade_receiver.district
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setDistrict(String district) {
		this.district = district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.address
	 * @return  the value of trade_receiver.address
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.address
	 * @param address  the value for trade_receiver.address
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.identity_card_type
	 * @return  the value of trade_receiver.identity_card_type
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public Byte getIdentityCardType() {
		return identityCardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.identity_card_type
	 * @param identityCardType  the value for trade_receiver.identity_card_type
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setIdentityCardType(Byte identityCardType) {
		this.identityCardType = identityCardType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.identity_card_no
	 * @return  the value of trade_receiver.identity_card_no
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public String getIdentityCardNo() {
		return identityCardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.identity_card_no
	 * @param identityCardNo  the value for trade_receiver.identity_card_no
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setIdentityCardNo(String identityCardNo) {
		this.identityCardNo = identityCardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.gmt_created
	 * @return  the value of trade_receiver.gmt_created
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public Date getGmtCreated() {
		return gmtCreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.gmt_created
	 * @param gmtCreated  the value for trade_receiver.gmt_created
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.gmt_modified
	 * @return  the value of trade_receiver.gmt_modified
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.gmt_modified
	 * @param gmtModified  the value for trade_receiver.gmt_modified
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_receiver.trade_id
	 * @return  the value of trade_receiver.trade_id
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public Long getTradeId() {
		return tradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_receiver.trade_id
	 * @param tradeId  the value for trade_receiver.trade_id
	 * @mbg.generated  Thu Apr 05 13:16:54 CST 2018
	 */
	public void setTradeId(Long tradeId) {
		this.tradeId = tradeId;
	}
}