package com.ycxy.wdgj.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TradeGoodsExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    public TradeGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBuyNumIsNull() {
            addCriterion("buy_num is null");
            return (Criteria) this;
        }

        public Criteria andBuyNumIsNotNull() {
            addCriterion("buy_num is not null");
            return (Criteria) this;
        }

        public Criteria andBuyNumEqualTo(Integer value) {
            addCriterion("buy_num =", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumNotEqualTo(Integer value) {
            addCriterion("buy_num <>", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumGreaterThan(Integer value) {
            addCriterion("buy_num >", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_num >=", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumLessThan(Integer value) {
            addCriterion("buy_num <", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumLessThanOrEqualTo(Integer value) {
            addCriterion("buy_num <=", value, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumIn(List<Integer> values) {
            addCriterion("buy_num in", values, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumNotIn(List<Integer> values) {
            addCriterion("buy_num not in", values, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumBetween(Integer value1, Integer value2) {
            addCriterion("buy_num between", value1, value2, "buyNum");
            return (Criteria) this;
        }

        public Criteria andBuyNumNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_num not between", value1, value2, "buyNum");
            return (Criteria) this;
        }

        public Criteria andTradeIdIsNull() {
            addCriterion("trade_id is null");
            return (Criteria) this;
        }

        public Criteria andTradeIdIsNotNull() {
            addCriterion("trade_id is not null");
            return (Criteria) this;
        }

        public Criteria andTradeIdEqualTo(Long value) {
            addCriterion("trade_id =", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdNotEqualTo(Long value) {
            addCriterion("trade_id <>", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdGreaterThan(Long value) {
            addCriterion("trade_id >", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("trade_id >=", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdLessThan(Long value) {
            addCriterion("trade_id <", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdLessThanOrEqualTo(Long value) {
            addCriterion("trade_id <=", value, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdIn(List<Long> values) {
            addCriterion("trade_id in", values, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdNotIn(List<Long> values) {
            addCriterion("trade_id not in", values, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdBetween(Long value1, Long value2) {
            addCriterion("trade_id between", value1, value2, "tradeId");
            return (Criteria) this;
        }

        public Criteria andTradeIdNotBetween(Long value1, Long value2) {
            addCriterion("trade_id not between", value1, value2, "tradeId");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdIsNull() {
            addCriterion("sub_trade_id is null");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdIsNotNull() {
            addCriterion("sub_trade_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdEqualTo(Long value) {
            addCriterion("sub_trade_id =", value, "subTradeId");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdNotEqualTo(Long value) {
            addCriterion("sub_trade_id <>", value, "subTradeId");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdGreaterThan(Long value) {
            addCriterion("sub_trade_id >", value, "subTradeId");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sub_trade_id >=", value, "subTradeId");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdLessThan(Long value) {
            addCriterion("sub_trade_id <", value, "subTradeId");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdLessThanOrEqualTo(Long value) {
            addCriterion("sub_trade_id <=", value, "subTradeId");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdIn(List<Long> values) {
            addCriterion("sub_trade_id in", values, "subTradeId");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdNotIn(List<Long> values) {
            addCriterion("sub_trade_id not in", values, "subTradeId");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdBetween(Long value1, Long value2) {
            addCriterion("sub_trade_id between", value1, value2, "subTradeId");
            return (Criteria) this;
        }

        public Criteria andSubTradeIdNotBetween(Long value1, Long value2) {
            addCriterion("sub_trade_id not between", value1, value2, "subTradeId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(String value) {
            addCriterion("goods_id =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(String value) {
            addCriterion("goods_id <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(String value) {
            addCriterion("goods_id >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(String value) {
            addCriterion("goods_id >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(String value) {
            addCriterion("goods_id <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(String value) {
            addCriterion("goods_id <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLike(String value) {
            addCriterion("goods_id like", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotLike(String value) {
            addCriterion("goods_id not like", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<String> values) {
            addCriterion("goods_id in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<String> values) {
            addCriterion("goods_id not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(String value1, String value2) {
            addCriterion("goods_id between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(String value1, String value2) {
            addCriterion("goods_id not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsNoIsNull() {
            addCriterion("goods_no is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNoIsNotNull() {
            addCriterion("goods_no is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNoEqualTo(String value) {
            addCriterion("goods_no =", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoNotEqualTo(String value) {
            addCriterion("goods_no <>", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoGreaterThan(String value) {
            addCriterion("goods_no >", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoGreaterThanOrEqualTo(String value) {
            addCriterion("goods_no >=", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoLessThan(String value) {
            addCriterion("goods_no <", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoLessThanOrEqualTo(String value) {
            addCriterion("goods_no <=", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoLike(String value) {
            addCriterion("goods_no like", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoNotLike(String value) {
            addCriterion("goods_no not like", value, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoIn(List<String> values) {
            addCriterion("goods_no in", values, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoNotIn(List<String> values) {
            addCriterion("goods_no not in", values, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoBetween(String value1, String value2) {
            addCriterion("goods_no between", value1, value2, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNoNotBetween(String value1, String value2) {
            addCriterion("goods_no not between", value1, value2, "goodsNo");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNull() {
            addCriterion("goods_name is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNotNull() {
            addCriterion("goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameEqualTo(String value) {
            addCriterion("goods_name =", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotEqualTo(String value) {
            addCriterion("goods_name <>", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThan(String value) {
            addCriterion("goods_name >", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("goods_name >=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThan(String value) {
            addCriterion("goods_name <", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("goods_name <=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLike(String value) {
            addCriterion("goods_name like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotLike(String value) {
            addCriterion("goods_name not like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIn(List<String> values) {
            addCriterion("goods_name in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotIn(List<String> values) {
            addCriterion("goods_name not in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameBetween(String value1, String value2) {
            addCriterion("goods_name between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotBetween(String value1, String value2) {
            addCriterion("goods_name not between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andSpecIdIsNull() {
            addCriterion("spec_id is null");
            return (Criteria) this;
        }

        public Criteria andSpecIdIsNotNull() {
            addCriterion("spec_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpecIdEqualTo(Long value) {
            addCriterion("spec_id =", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdNotEqualTo(Long value) {
            addCriterion("spec_id <>", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdGreaterThan(Long value) {
            addCriterion("spec_id >", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdGreaterThanOrEqualTo(Long value) {
            addCriterion("spec_id >=", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdLessThan(Long value) {
            addCriterion("spec_id <", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdLessThanOrEqualTo(Long value) {
            addCriterion("spec_id <=", value, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdIn(List<Long> values) {
            addCriterion("spec_id in", values, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdNotIn(List<Long> values) {
            addCriterion("spec_id not in", values, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdBetween(Long value1, Long value2) {
            addCriterion("spec_id between", value1, value2, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecIdNotBetween(Long value1, Long value2) {
            addCriterion("spec_id not between", value1, value2, "specId");
            return (Criteria) this;
        }

        public Criteria andSpecNameIsNull() {
            addCriterion("spec_name is null");
            return (Criteria) this;
        }

        public Criteria andSpecNameIsNotNull() {
            addCriterion("spec_name is not null");
            return (Criteria) this;
        }

        public Criteria andSpecNameEqualTo(String value) {
            addCriterion("spec_name =", value, "specName");
            return (Criteria) this;
        }

        public Criteria andSpecNameNotEqualTo(String value) {
            addCriterion("spec_name <>", value, "specName");
            return (Criteria) this;
        }

        public Criteria andSpecNameGreaterThan(String value) {
            addCriterion("spec_name >", value, "specName");
            return (Criteria) this;
        }

        public Criteria andSpecNameGreaterThanOrEqualTo(String value) {
            addCriterion("spec_name >=", value, "specName");
            return (Criteria) this;
        }

        public Criteria andSpecNameLessThan(String value) {
            addCriterion("spec_name <", value, "specName");
            return (Criteria) this;
        }

        public Criteria andSpecNameLessThanOrEqualTo(String value) {
            addCriterion("spec_name <=", value, "specName");
            return (Criteria) this;
        }

        public Criteria andSpecNameLike(String value) {
            addCriterion("spec_name like", value, "specName");
            return (Criteria) this;
        }

        public Criteria andSpecNameNotLike(String value) {
            addCriterion("spec_name not like", value, "specName");
            return (Criteria) this;
        }

        public Criteria andSpecNameIn(List<String> values) {
            addCriterion("spec_name in", values, "specName");
            return (Criteria) this;
        }

        public Criteria andSpecNameNotIn(List<String> values) {
            addCriterion("spec_name not in", values, "specName");
            return (Criteria) this;
        }

        public Criteria andSpecNameBetween(String value1, String value2) {
            addCriterion("spec_name between", value1, value2, "specName");
            return (Criteria) this;
        }

        public Criteria andSpecNameNotBetween(String value1, String value2) {
            addCriterion("spec_name not between", value1, value2, "specName");
            return (Criteria) this;
        }

        public Criteria andBarcodeIsNull() {
            addCriterion("barcode is null");
            return (Criteria) this;
        }

        public Criteria andBarcodeIsNotNull() {
            addCriterion("barcode is not null");
            return (Criteria) this;
        }

        public Criteria andBarcodeEqualTo(String value) {
            addCriterion("barcode =", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotEqualTo(String value) {
            addCriterion("barcode <>", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeGreaterThan(String value) {
            addCriterion("barcode >", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeGreaterThanOrEqualTo(String value) {
            addCriterion("barcode >=", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLessThan(String value) {
            addCriterion("barcode <", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLessThanOrEqualTo(String value) {
            addCriterion("barcode <=", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeLike(String value) {
            addCriterion("barcode like", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotLike(String value) {
            addCriterion("barcode not like", value, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeIn(List<String> values) {
            addCriterion("barcode in", values, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotIn(List<String> values) {
            addCriterion("barcode not in", values, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeBetween(String value1, String value2) {
            addCriterion("barcode between", value1, value2, "barcode");
            return (Criteria) this;
        }

        public Criteria andBarcodeNotBetween(String value1, String value2) {
            addCriterion("barcode not between", value1, value2, "barcode");
            return (Criteria) this;
        }

        public Criteria andSellCountIsNull() {
            addCriterion("sell_count is null");
            return (Criteria) this;
        }

        public Criteria andSellCountIsNotNull() {
            addCriterion("sell_count is not null");
            return (Criteria) this;
        }

        public Criteria andSellCountEqualTo(Integer value) {
            addCriterion("sell_count =", value, "sellCount");
            return (Criteria) this;
        }

        public Criteria andSellCountNotEqualTo(Integer value) {
            addCriterion("sell_count <>", value, "sellCount");
            return (Criteria) this;
        }

        public Criteria andSellCountGreaterThan(Integer value) {
            addCriterion("sell_count >", value, "sellCount");
            return (Criteria) this;
        }

        public Criteria andSellCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("sell_count >=", value, "sellCount");
            return (Criteria) this;
        }

        public Criteria andSellCountLessThan(Integer value) {
            addCriterion("sell_count <", value, "sellCount");
            return (Criteria) this;
        }

        public Criteria andSellCountLessThanOrEqualTo(Integer value) {
            addCriterion("sell_count <=", value, "sellCount");
            return (Criteria) this;
        }

        public Criteria andSellCountIn(List<Integer> values) {
            addCriterion("sell_count in", values, "sellCount");
            return (Criteria) this;
        }

        public Criteria andSellCountNotIn(List<Integer> values) {
            addCriterion("sell_count not in", values, "sellCount");
            return (Criteria) this;
        }

        public Criteria andSellCountBetween(Integer value1, Integer value2) {
            addCriterion("sell_count between", value1, value2, "sellCount");
            return (Criteria) this;
        }

        public Criteria andSellCountNotBetween(Integer value1, Integer value2) {
            addCriterion("sell_count not between", value1, value2, "sellCount");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("unit is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("unit is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("unit =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("unit <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("unit >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("unit >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("unit <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("unit <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("unit like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("unit not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("unit in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("unit not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("unit between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("unit not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andSellPriceIsNull() {
            addCriterion("sell_price is null");
            return (Criteria) this;
        }

        public Criteria andSellPriceIsNotNull() {
            addCriterion("sell_price is not null");
            return (Criteria) this;
        }

        public Criteria andSellPriceEqualTo(Long value) {
            addCriterion("sell_price =", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceNotEqualTo(Long value) {
            addCriterion("sell_price <>", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceGreaterThan(Long value) {
            addCriterion("sell_price >", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("sell_price >=", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceLessThan(Long value) {
            addCriterion("sell_price <", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceLessThanOrEqualTo(Long value) {
            addCriterion("sell_price <=", value, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceIn(List<Long> values) {
            addCriterion("sell_price in", values, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceNotIn(List<Long> values) {
            addCriterion("sell_price not in", values, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceBetween(Long value1, Long value2) {
            addCriterion("sell_price between", value1, value2, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellPriceNotBetween(Long value1, Long value2) {
            addCriterion("sell_price not between", value1, value2, "sellPrice");
            return (Criteria) this;
        }

        public Criteria andSellTotalIsNull() {
            addCriterion("sell_total is null");
            return (Criteria) this;
        }

        public Criteria andSellTotalIsNotNull() {
            addCriterion("sell_total is not null");
            return (Criteria) this;
        }

        public Criteria andSellTotalEqualTo(Long value) {
            addCriterion("sell_total =", value, "sellTotal");
            return (Criteria) this;
        }

        public Criteria andSellTotalNotEqualTo(Long value) {
            addCriterion("sell_total <>", value, "sellTotal");
            return (Criteria) this;
        }

        public Criteria andSellTotalGreaterThan(Long value) {
            addCriterion("sell_total >", value, "sellTotal");
            return (Criteria) this;
        }

        public Criteria andSellTotalGreaterThanOrEqualTo(Long value) {
            addCriterion("sell_total >=", value, "sellTotal");
            return (Criteria) this;
        }

        public Criteria andSellTotalLessThan(Long value) {
            addCriterion("sell_total <", value, "sellTotal");
            return (Criteria) this;
        }

        public Criteria andSellTotalLessThanOrEqualTo(Long value) {
            addCriterion("sell_total <=", value, "sellTotal");
            return (Criteria) this;
        }

        public Criteria andSellTotalIn(List<Long> values) {
            addCriterion("sell_total in", values, "sellTotal");
            return (Criteria) this;
        }

        public Criteria andSellTotalNotIn(List<Long> values) {
            addCriterion("sell_total not in", values, "sellTotal");
            return (Criteria) this;
        }

        public Criteria andSellTotalBetween(Long value1, Long value2) {
            addCriterion("sell_total between", value1, value2, "sellTotal");
            return (Criteria) this;
        }

        public Criteria andSellTotalNotBetween(Long value1, Long value2) {
            addCriterion("sell_total not between", value1, value2, "sellTotal");
            return (Criteria) this;
        }

        public Criteria andTaxFeeIsNull() {
            addCriterion("tax_fee is null");
            return (Criteria) this;
        }

        public Criteria andTaxFeeIsNotNull() {
            addCriterion("tax_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTaxFeeEqualTo(Long value) {
            addCriterion("tax_fee =", value, "taxFee");
            return (Criteria) this;
        }

        public Criteria andTaxFeeNotEqualTo(Long value) {
            addCriterion("tax_fee <>", value, "taxFee");
            return (Criteria) this;
        }

        public Criteria andTaxFeeGreaterThan(Long value) {
            addCriterion("tax_fee >", value, "taxFee");
            return (Criteria) this;
        }

        public Criteria andTaxFeeGreaterThanOrEqualTo(Long value) {
            addCriterion("tax_fee >=", value, "taxFee");
            return (Criteria) this;
        }

        public Criteria andTaxFeeLessThan(Long value) {
            addCriterion("tax_fee <", value, "taxFee");
            return (Criteria) this;
        }

        public Criteria andTaxFeeLessThanOrEqualTo(Long value) {
            addCriterion("tax_fee <=", value, "taxFee");
            return (Criteria) this;
        }

        public Criteria andTaxFeeIn(List<Long> values) {
            addCriterion("tax_fee in", values, "taxFee");
            return (Criteria) this;
        }

        public Criteria andTaxFeeNotIn(List<Long> values) {
            addCriterion("tax_fee not in", values, "taxFee");
            return (Criteria) this;
        }

        public Criteria andTaxFeeBetween(Long value1, Long value2) {
            addCriterion("tax_fee between", value1, value2, "taxFee");
            return (Criteria) this;
        }

        public Criteria andTaxFeeNotBetween(Long value1, Long value2) {
            addCriterion("tax_fee not between", value1, value2, "taxFee");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoIsNull() {
            addCriterion("goods_memo is null");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoIsNotNull() {
            addCriterion("goods_memo is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoEqualTo(String value) {
            addCriterion("goods_memo =", value, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoNotEqualTo(String value) {
            addCriterion("goods_memo <>", value, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoGreaterThan(String value) {
            addCriterion("goods_memo >", value, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoGreaterThanOrEqualTo(String value) {
            addCriterion("goods_memo >=", value, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoLessThan(String value) {
            addCriterion("goods_memo <", value, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoLessThanOrEqualTo(String value) {
            addCriterion("goods_memo <=", value, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoLike(String value) {
            addCriterion("goods_memo like", value, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoNotLike(String value) {
            addCriterion("goods_memo not like", value, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoIn(List<String> values) {
            addCriterion("goods_memo in", values, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoNotIn(List<String> values) {
            addCriterion("goods_memo not in", values, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoBetween(String value1, String value2) {
            addCriterion("goods_memo between", value1, value2, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andGoodsMemoNotBetween(String value1, String value2) {
            addCriterion("goods_memo not between", value1, value2, "goodsMemo");
            return (Criteria) this;
        }

        public Criteria andIsFitIsNull() {
            addCriterion("is_fit is null");
            return (Criteria) this;
        }

        public Criteria andIsFitIsNotNull() {
            addCriterion("is_fit is not null");
            return (Criteria) this;
        }

        public Criteria andIsFitEqualTo(Byte value) {
            addCriterion("is_fit =", value, "isFit");
            return (Criteria) this;
        }

        public Criteria andIsFitNotEqualTo(Byte value) {
            addCriterion("is_fit <>", value, "isFit");
            return (Criteria) this;
        }

        public Criteria andIsFitGreaterThan(Byte value) {
            addCriterion("is_fit >", value, "isFit");
            return (Criteria) this;
        }

        public Criteria andIsFitGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_fit >=", value, "isFit");
            return (Criteria) this;
        }

        public Criteria andIsFitLessThan(Byte value) {
            addCriterion("is_fit <", value, "isFit");
            return (Criteria) this;
        }

        public Criteria andIsFitLessThanOrEqualTo(Byte value) {
            addCriterion("is_fit <=", value, "isFit");
            return (Criteria) this;
        }

        public Criteria andIsFitIn(List<Byte> values) {
            addCriterion("is_fit in", values, "isFit");
            return (Criteria) this;
        }

        public Criteria andIsFitNotIn(List<Byte> values) {
            addCriterion("is_fit not in", values, "isFit");
            return (Criteria) this;
        }

        public Criteria andIsFitBetween(Byte value1, Byte value2) {
            addCriterion("is_fit between", value1, value2, "isFit");
            return (Criteria) this;
        }

        public Criteria andIsFitNotBetween(Byte value1, Byte value2) {
            addCriterion("is_fit not between", value1, value2, "isFit");
            return (Criteria) this;
        }

        public Criteria andIsGiftIsNull() {
            addCriterion("is_gift is null");
            return (Criteria) this;
        }

        public Criteria andIsGiftIsNotNull() {
            addCriterion("is_gift is not null");
            return (Criteria) this;
        }

        public Criteria andIsGiftEqualTo(Byte value) {
            addCriterion("is_gift =", value, "isGift");
            return (Criteria) this;
        }

        public Criteria andIsGiftNotEqualTo(Byte value) {
            addCriterion("is_gift <>", value, "isGift");
            return (Criteria) this;
        }

        public Criteria andIsGiftGreaterThan(Byte value) {
            addCriterion("is_gift >", value, "isGift");
            return (Criteria) this;
        }

        public Criteria andIsGiftGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_gift >=", value, "isGift");
            return (Criteria) this;
        }

        public Criteria andIsGiftLessThan(Byte value) {
            addCriterion("is_gift <", value, "isGift");
            return (Criteria) this;
        }

        public Criteria andIsGiftLessThanOrEqualTo(Byte value) {
            addCriterion("is_gift <=", value, "isGift");
            return (Criteria) this;
        }

        public Criteria andIsGiftIn(List<Byte> values) {
            addCriterion("is_gift in", values, "isGift");
            return (Criteria) this;
        }

        public Criteria andIsGiftNotIn(List<Byte> values) {
            addCriterion("is_gift not in", values, "isGift");
            return (Criteria) this;
        }

        public Criteria andIsGiftBetween(Byte value1, Byte value2) {
            addCriterion("is_gift between", value1, value2, "isGift");
            return (Criteria) this;
        }

        public Criteria andIsGiftNotBetween(Byte value1, Byte value2) {
            addCriterion("is_gift not between", value1, value2, "isGift");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusIsNull() {
            addCriterion("sub_trade_status is null");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusIsNotNull() {
            addCriterion("sub_trade_status is not null");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusEqualTo(Byte value) {
            addCriterion("sub_trade_status =", value, "subTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusNotEqualTo(Byte value) {
            addCriterion("sub_trade_status <>", value, "subTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusGreaterThan(Byte value) {
            addCriterion("sub_trade_status >", value, "subTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("sub_trade_status >=", value, "subTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusLessThan(Byte value) {
            addCriterion("sub_trade_status <", value, "subTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusLessThanOrEqualTo(Byte value) {
            addCriterion("sub_trade_status <=", value, "subTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusIn(List<Byte> values) {
            addCriterion("sub_trade_status in", values, "subTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusNotIn(List<Byte> values) {
            addCriterion("sub_trade_status not in", values, "subTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusBetween(Byte value1, Byte value2) {
            addCriterion("sub_trade_status between", value1, value2, "subTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSubTradeStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("sub_trade_status not between", value1, value2, "subTradeStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusIsNull() {
            addCriterion("refund_status is null");
            return (Criteria) this;
        }

        public Criteria andRefundStatusIsNotNull() {
            addCriterion("refund_status is not null");
            return (Criteria) this;
        }

        public Criteria andRefundStatusEqualTo(Byte value) {
            addCriterion("refund_status =", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusNotEqualTo(Byte value) {
            addCriterion("refund_status <>", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusGreaterThan(Byte value) {
            addCriterion("refund_status >", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("refund_status >=", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusLessThan(Byte value) {
            addCriterion("refund_status <", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusLessThanOrEqualTo(Byte value) {
            addCriterion("refund_status <=", value, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusIn(List<Byte> values) {
            addCriterion("refund_status in", values, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusNotIn(List<Byte> values) {
            addCriterion("refund_status not in", values, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusBetween(Byte value1, Byte value2) {
            addCriterion("refund_status between", value1, value2, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andRefundStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("refund_status not between", value1, value2, "refundStatus");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoIsNull() {
            addCriterion("trade_goods_no is null");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoIsNotNull() {
            addCriterion("trade_goods_no is not null");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoEqualTo(Long value) {
            addCriterion("trade_goods_no =", value, "tradeGoodsNo");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoNotEqualTo(Long value) {
            addCriterion("trade_goods_no <>", value, "tradeGoodsNo");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoGreaterThan(Long value) {
            addCriterion("trade_goods_no >", value, "tradeGoodsNo");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoGreaterThanOrEqualTo(Long value) {
            addCriterion("trade_goods_no >=", value, "tradeGoodsNo");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoLessThan(Long value) {
            addCriterion("trade_goods_no <", value, "tradeGoodsNo");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoLessThanOrEqualTo(Long value) {
            addCriterion("trade_goods_no <=", value, "tradeGoodsNo");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoIn(List<Long> values) {
            addCriterion("trade_goods_no in", values, "tradeGoodsNo");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoNotIn(List<Long> values) {
            addCriterion("trade_goods_no not in", values, "tradeGoodsNo");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoBetween(Long value1, Long value2) {
            addCriterion("trade_goods_no between", value1, value2, "tradeGoodsNo");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNoNotBetween(Long value1, Long value2) {
            addCriterion("trade_goods_no not between", value1, value2, "tradeGoodsNo");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameIsNull() {
            addCriterion("trade_goods_name is null");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameIsNotNull() {
            addCriterion("trade_goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameEqualTo(String value) {
            addCriterion("trade_goods_name =", value, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameNotEqualTo(String value) {
            addCriterion("trade_goods_name <>", value, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameGreaterThan(String value) {
            addCriterion("trade_goods_name >", value, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("trade_goods_name >=", value, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameLessThan(String value) {
            addCriterion("trade_goods_name <", value, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("trade_goods_name <=", value, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameLike(String value) {
            addCriterion("trade_goods_name like", value, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameNotLike(String value) {
            addCriterion("trade_goods_name not like", value, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameIn(List<String> values) {
            addCriterion("trade_goods_name in", values, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameNotIn(List<String> values) {
            addCriterion("trade_goods_name not in", values, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameBetween(String value1, String value2) {
            addCriterion("trade_goods_name between", value1, value2, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsNameNotBetween(String value1, String value2) {
            addCriterion("trade_goods_name not between", value1, value2, "tradeGoodsName");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecIsNull() {
            addCriterion("trade_goods_spec is null");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecIsNotNull() {
            addCriterion("trade_goods_spec is not null");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecEqualTo(String value) {
            addCriterion("trade_goods_spec =", value, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecNotEqualTo(String value) {
            addCriterion("trade_goods_spec <>", value, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecGreaterThan(String value) {
            addCriterion("trade_goods_spec >", value, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecGreaterThanOrEqualTo(String value) {
            addCriterion("trade_goods_spec >=", value, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecLessThan(String value) {
            addCriterion("trade_goods_spec <", value, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecLessThanOrEqualTo(String value) {
            addCriterion("trade_goods_spec <=", value, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecLike(String value) {
            addCriterion("trade_goods_spec like", value, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecNotLike(String value) {
            addCriterion("trade_goods_spec not like", value, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecIn(List<String> values) {
            addCriterion("trade_goods_spec in", values, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecNotIn(List<String> values) {
            addCriterion("trade_goods_spec not in", values, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecBetween(String value1, String value2) {
            addCriterion("trade_goods_spec between", value1, value2, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsSpecNotBetween(String value1, String value2) {
            addCriterion("trade_goods_spec not between", value1, value2, "tradeGoodsSpec");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitIsNull() {
            addCriterion("trade_goods_unit is null");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitIsNotNull() {
            addCriterion("trade_goods_unit is not null");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitEqualTo(String value) {
            addCriterion("trade_goods_unit =", value, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitNotEqualTo(String value) {
            addCriterion("trade_goods_unit <>", value, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitGreaterThan(String value) {
            addCriterion("trade_goods_unit >", value, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitGreaterThanOrEqualTo(String value) {
            addCriterion("trade_goods_unit >=", value, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitLessThan(String value) {
            addCriterion("trade_goods_unit <", value, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitLessThanOrEqualTo(String value) {
            addCriterion("trade_goods_unit <=", value, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitLike(String value) {
            addCriterion("trade_goods_unit like", value, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitNotLike(String value) {
            addCriterion("trade_goods_unit not like", value, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitIn(List<String> values) {
            addCriterion("trade_goods_unit in", values, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitNotIn(List<String> values) {
            addCriterion("trade_goods_unit not in", values, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitBetween(String value1, String value2) {
            addCriterion("trade_goods_unit between", value1, value2, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andTradeGoodsUnitNotBetween(String value1, String value2) {
            addCriterion("trade_goods_unit not between", value1, value2, "tradeGoodsUnit");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoIsNull() {
            addCriterion("source_trade_no is null");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoIsNotNull() {
            addCriterion("source_trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoEqualTo(Long value) {
            addCriterion("source_trade_no =", value, "sourceTradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoNotEqualTo(Long value) {
            addCriterion("source_trade_no <>", value, "sourceTradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoGreaterThan(Long value) {
            addCriterion("source_trade_no >", value, "sourceTradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoGreaterThanOrEqualTo(Long value) {
            addCriterion("source_trade_no >=", value, "sourceTradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoLessThan(Long value) {
            addCriterion("source_trade_no <", value, "sourceTradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoLessThanOrEqualTo(Long value) {
            addCriterion("source_trade_no <=", value, "sourceTradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoIn(List<Long> values) {
            addCriterion("source_trade_no in", values, "sourceTradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoNotIn(List<Long> values) {
            addCriterion("source_trade_no not in", values, "sourceTradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoBetween(Long value1, Long value2) {
            addCriterion("source_trade_no between", value1, value2, "sourceTradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceTradeNoNotBetween(Long value1, Long value2) {
            addCriterion("source_trade_no not between", value1, value2, "sourceTradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoIsNull() {
            addCriterion("source_subtrade_no is null");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoIsNotNull() {
            addCriterion("source_subtrade_no is not null");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoEqualTo(Long value) {
            addCriterion("source_subtrade_no =", value, "sourceSubtradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoNotEqualTo(Long value) {
            addCriterion("source_subtrade_no <>", value, "sourceSubtradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoGreaterThan(Long value) {
            addCriterion("source_subtrade_no >", value, "sourceSubtradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoGreaterThanOrEqualTo(Long value) {
            addCriterion("source_subtrade_no >=", value, "sourceSubtradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoLessThan(Long value) {
            addCriterion("source_subtrade_no <", value, "sourceSubtradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoLessThanOrEqualTo(Long value) {
            addCriterion("source_subtrade_no <=", value, "sourceSubtradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoIn(List<Long> values) {
            addCriterion("source_subtrade_no in", values, "sourceSubtradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoNotIn(List<Long> values) {
            addCriterion("source_subtrade_no not in", values, "sourceSubtradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoBetween(Long value1, Long value2) {
            addCriterion("source_subtrade_no between", value1, value2, "sourceSubtradeNo");
            return (Criteria) this;
        }

        public Criteria andSourceSubtradeNoNotBetween(Long value1, Long value2) {
            addCriterion("source_subtrade_no not between", value1, value2, "sourceSubtradeNo");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusIsNull() {
            addCriterion("souce_trade_status is null");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusIsNotNull() {
            addCriterion("souce_trade_status is not null");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusEqualTo(Byte value) {
            addCriterion("souce_trade_status =", value, "souceTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusNotEqualTo(Byte value) {
            addCriterion("souce_trade_status <>", value, "souceTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusGreaterThan(Byte value) {
            addCriterion("souce_trade_status >", value, "souceTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("souce_trade_status >=", value, "souceTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusLessThan(Byte value) {
            addCriterion("souce_trade_status <", value, "souceTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusLessThanOrEqualTo(Byte value) {
            addCriterion("souce_trade_status <=", value, "souceTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusIn(List<Byte> values) {
            addCriterion("souce_trade_status in", values, "souceTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusNotIn(List<Byte> values) {
            addCriterion("souce_trade_status not in", values, "souceTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusBetween(Byte value1, Byte value2) {
            addCriterion("souce_trade_status between", value1, value2, "souceTradeStatus");
            return (Criteria) this;
        }

        public Criteria andSouceTradeStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("souce_trade_status not between", value1, value2, "souceTradeStatus");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Byte value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Byte value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Byte value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Byte value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Byte value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Byte> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Byte> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Byte value1, Byte value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Byte value1, Byte value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table trade_goods
     * @mbg.generated  Fri Feb 23 09:36:54 CST 2018
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_goods
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 21 20:08:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}